CREATE TABLE CMT_STTLMNT_STC_DATA_ENTR_STR (
ID                              NUMBER NOT NULL PRIMARY KEY,
LAST_UPDATE                     TIMESTAMP(6),
VERSION                         NUMBER,
SETTLEMENT_STATIC_DATA_ENTR_ID  NUMBER
);
COMMENT ON COLUMN CMT_STTLMNT_STC_DATA_ENTR_STR.ID IS 'Primary key';
COMMENT ON COLUMN CMT_STTLMNT_STC_DATA_ENTR_STR.LAST_UPDATE IS 'Timestamp of last modification';
COMMENT ON COLUMN CMT_STTLMNT_STC_DATA_ENTR_STR.VERSION IS 'Row modification counter used for optimistic locking';
COMMENT ON COLUMN CMT_STTLMNT_STC_DATA_ENTR_STR.SETTLEMENT_STATIC_DATA_ENTR_ID IS 'Foreign key to Settlement Static Data Entry table';

