
# zbudowac od nowa obrazy:
# docker compose down
# docker compose build --no-cache backend
# docker compose up -d

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: jobhigh_db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - jobhigh_network

  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile.dev
    container_name: jobhigh_backend
    env_file:
      - .env
    expose:
      - "3100"
    ports:
      - "3100:3100"
      - "9229:9229"
    depends_on:
      - db
    volumes:
      - ./backend:/app/backend
      - ./shared:/app/shared
      - /app/backend/node_modules
    networks:
      - jobhigh_network
    command: ["npm", "run", "start:nodemon-debug"]
    # command: ["npm", "run", "start:nodemon"]

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
        - REACT_APP_FIREBASE_API_KEY=${REACT_APP_FIREBASE_API_KEY}
        - REACT_APP_FIREBASE_AUTH_DOMAIN=${REACT_APP_FIREBASE_AUTH_DOMAIN}
        - REACT_APP_FIREBASE_PROJECT_ID=${REACT_APP_FIREBASE_PROJECT_ID}
        - REACT_APP_FIREBASE_APP_ID=${REACT_APP_FIREBASE_APP_ID}
        - REACT_APP_GOOGLE_MAPS_API_KEY=${REACT_APP_GOOGLE_MAPS_API_KEY}
        - REACT_APP_CLOUDINARY_CLOUD_NAME=${REACT_APP_CLOUDINARY_CLOUD_NAME}
        - REACT_APP_CLOUDINARY_UPLOAD_PRESET=${REACT_APP_CLOUDINARY_UPLOAD_PRESET}
    container_name: jobhigh_frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend
    networks:
      - jobhigh_network

volumes:
  postgres_data:

networks:
  jobhigh_network:
    driver: bridge
