
# zbudowac od nowa obrazy:
# docker compose down
# docker compose build --no-cache backend
# docker compose up -d

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: jobhigh_db
    environment:
      POSTGRES_DB: jobhigh_db
      POSTGRES_USER: jobhigh_user
      POSTGRES_PASSWORD: jobhigh_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - jobhigh_network

  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile.dev
    container_name: jobhigh_backend
    env_file:
      - .env
    expose:
      - "3100"
    ports:
      - "3100:3100"
      - "9229:9229"
    depends_on:
      - db
    volumes:
      - ./backend:/app/backend
      - ./shared:/app/shared
      - /app/backend/node_modules
    networks:
      - jobhigh_network
    # command: ["npm", "run", "start:nodemon-debug"]
    command: ["npm", "run", "start:nodemon"]

  nginx:
    image: nginx:alpine
    container_name: jobhigh_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
    depends_on:
      - backend
    networks:
      - jobhigh_network

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: frontend/Dockerfile
  #   container_name: jobhigh_frontend
  #   environment:
  #     REACT_APP_API_URL: http://localhost:3100/api
  #     NODE_ENV: development
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   networks:
  #     - jobhigh_network
  #   command: npm start

volumes:
  postgres_data:

networks:
  jobhigh_network:
    driver: bridge
