FROM node:18-alpine

WORKDIR /app/backend

# Kopiuj package*.json i instaluj zależności
COPY backend/package*.json ./
RUN npm ci && npm cache clean --force

# Kopiuj kod backendu
# COPY backend /app/backend
# Kopiuj katalog shared z root do /app/shared
# COPY shared /app/backend/shared

EXPOSE 3100

CMD ["npm", "run", "start:nodemon"]
