import { IconType } from "react-icons";
import { FaBan, FaBars, FaBell, FaBookmark, FaBriefcase, FaCalendarAlt, FaCheck, FaChevronRight, FaCog, FaComments, FaDownload, FaEdit, FaEllipsisV, FaFilter, FaGlobe, FaHome, FaIdCard, FaMapMarker, FaMapMarkerAlt, FaMarker, FaPaperPlane, FaPhone, FaPlus, FaRegBookmark, FaRegClock, FaRegCompass, FaRegEnvelope, FaRegStar, FaRulerVertical, FaSearch, FaSignInAlt, FaSignOutAlt, FaSlidersH, FaStar, FaStream, FaTags, FaTimes, FaTrash, FaUserCircle, FaUserFriends, FaUserPlus } from "react-icons/fa";
import { MdThumbUp, MdVisibility } from "react-icons/md";

export const Ico = {
    HOME: FaHome,
    MENU: FaEllipsisV,
    BURGER: FaStream,
    FRIENDS: FaUserFriends,
    CHAT: FaComments,
    MSG: FaPaperPlane,
    NOTIFICATION: FaBell,
    ACCOUNT: FaUserCircle,
    SIGN_IN: FaSignInAlt,
    SIGN_OUT: FaSignOutAlt,
    OFFER: FaBriefcase,
    WORKER: FaIdCard,
    DELETE: FaTrash,
    CANCEL: FaTimes,
    PHONE: FaPhone,
    SEARCH: FaSearch,
    ADD_USER: FaUserPlus,
    SETTINGS: FaCog,
    EMPTY: FaBan,
    CATEGORIES: FaTags,
    LANGUAGE: FaGlobe,
    MARKER: FaMapMarkerAlt,
    CALENDAR: FaCalendarAlt,
    EDIT: FaEdit,
    CHECK: FaCheck,
    DOWNLOAD: FaDownload,
    FILTER: FaFilter,
    SLIDERS: FaSlidersH,
    CHEVRON_RIGHT: FaChevronRight,
    CLOCK: FaRegClock,
    RULER: FaRulerVertical,
    COMPASS: FaRegCompass,
    EMAIL: FaRegEnvelope,
    PLUS: FaPlus,
    BOOKMARK: FaBookmark,
    BOOKMARK_OUTLINE: FaRegBookmark ,
    FEATURED: FaStar,
    VIEWS: MdVisibility,
    LIKES: MdThumbUp,
    STAR: FaStar,
    STAR_OUTLINE: FaRegStar,
} as const satisfies Record<string, IconType>