import { IconType } from "react-icons";
import { FaBan, FaBell, FaBriefcase, FaCalendarAlt, FaCheck, FaChevronRight, FaCog, FaComments, FaDownload, FaEdit, FaEllipsisV, FaFilter, FaGlobe, FaHome, FaIdCard, FaMapMarker, FaMapMarkerAlt, FaMarker, FaPaperPlane, FaPhone, FaRegClock, FaRegCompass, FaRegEnvelope, FaRulerVertical, FaSearch, FaSignInAlt, FaSignOutAlt, FaSlidersH, FaTags, FaTimes, FaTrash, FaUserCircle, FaUserFriends, FaUserPlus } from "react-icons/fa";

export const Ico = {
    HOME: FaHome,
    MENU: FaEllipsisV,
    FRIENDS: FaUserFriends,
    CHAT: FaComments,
    MSG: FaPaperPlane,
    NOTIFICATION: FaBell,
    ACCOUNT: FaUserCircle,
    SIGN_IN: FaSignInAlt,
    SIGN_OUT: FaSignOutAlt,
    OFFER: FaBriefcase,
    WORKER: FaIdCard,
    DELETE: FaTrash,
    CANCEL: FaTimes,
    PHONE: FaPhone,
    SEARCH: FaSearch,
    ADD_USER: FaUserPlus,
    SETTINGS: FaCog,
    EMPTY: FaBan,
    CATEGORIES: FaTags,
    LANGUAGE: FaGlobe,
    MARKER: FaMapMarkerAlt,
    CALENDAR: FaCalendarAlt,
    EDIT: FaEdit,
    CHECK: FaCheck,
    DOWNLOAD: FaDownload,
    FILTER: FaFilter,
    SLIDERS: FaSlidersH,
    CHEVRON_RIGHT: FaChevronRight,
    CLOCK: FaRegClock,
    RULER: FaRulerVertical,
    COMPASS: FaRegCompass,
    EMAIL: FaRegEnvelope,
} as const satisfies Record<string, IconType>