
/** Created by Pawel Malek **/
import { Injectable, Logger } from '@nestjs/common';
import { FirebaseConfig } from './FirebaseConfig';
import { DecodedIdToken, UserRecord } from 'firebase-admin/auth';
import { UserService } from 'user/services/UserService';
import { Util } from '@shared/utils/util';
import { UserI, UserStatuses } from '@shared/interfaces/UserI';
import { UserUtil } from 'user/UserUtil';
import { AuthService } from './AuthService';
import { TelegramUtil } from 'telegram/util/telegram.util';
import { ConfigService } from '@nestjs/config';
import { BehaviorSubject } from 'rxjs/internal/BehaviorSubject';
import { LoginFormDto, TelegramLoginPin } from '@shared/dto/AuthDto';
import { Subject } from 'rxjs';

const generateFourDigitsPin = () => {
  return Math.floor(1000 + Math.random() * 9000).toString();
}

@Injectable()
export class ExportedAuthService {

  private readonly logger = new Logger(this.constructor.name);

  constructor(
    private readonly firebaseConfig: FirebaseConfig,
    private readonly userService: UserService,
    private readonly authService: AuthService,
    private readonly configService: ConfigService,
  ) { }

  private pins$ = new BehaviorSubject<Set<TelegramLoginPin>>(new Set());

  public autogeneratedPin$ = new Subject<string>();

  public autoGenerate = async (telegramChannelId: string): Promise<boolean> => {
    const user = await this.userService.getUserByTelegramChannelId(telegramChannelId);
    if (!user) {
      this.logger.warn(`No user found for telegramChannelId ${telegramChannelId} while triggering auto-generate`);
      return false;
    }
    const pin = this.generatePin(telegramChannelId);
    this.autogeneratedPin$.next(telegramChannelId);
  }

  public loginByPin = async (pin: string): Promise<LoginFormDto | null> => {
    const pins = this.filterExpiredPins().filter(pinObj => pinObj.pin === pin);
    if (!pins.length) {
      this.logger.warn(`Invalid or expired login pin attempted: ${pin}`);
      return null;
    }
    const p = pins[0];
    const telegramChannelId = p.telegramChannelId;
    const user = await this.userService.getUserByTelegramChannelId(telegramChannelId);
    if (!user) {
      this.logger.warn(`No user found for telegramChannelId ${telegramChannelId} while logging in with pin ${pin}`);
      return null;
    }

    const credentials = TelegramUtil.prepareCredentials(telegramChannelId, this.getSecretKey());
    this.deactivatePin(pin, telegramChannelId);
    return credentials;
  }

  private deactivatePin = (pin: string, telegramChannelId: string) => {
    const existingPins = Array.from(this.pins$.getValue());
    const filteredPins = existingPins.filter(pinObj => pinObj.pin !== pin || pinObj.telegramChannelId !== telegramChannelId);
    this.pins$.next(new Set(filteredPins));
  }

  public getLoginPin = (telegramChannelId: string): TelegramLoginPin | null => {
    const pins = this.filterExpiredPins().filter(pinObj => pinObj.telegramChannelId === telegramChannelId);
    if (pins.length) {
      return pins[0];
    }
    return null;
  }

  private filterExpiredPins = (): TelegramLoginPin[] => {
    const now = new Date();
    const validPins = Array.from(this.pins$.getValue()).filter(pinObj => {
      const diff = (now.getTime() - pinObj.created.getTime()) / 1000 / 60; // minutes
      return diff <= 15;
    });
    return validPins;
  }

  public generatePin = (telegramChannelId: string): TelegramLoginPin => {
    const newPin: TelegramLoginPin = {
      created: new Date(),
      pin: generateFourDigitsPin(),
      telegramChannelId: telegramChannelId,
    }
    this.pins$.next(new Set([...this.pins$.getValue(), newPin]));
    this.logger.log(`Generated new login pin for user ${telegramChannelId}: ${newPin.pin}`);
    return newPin;
  }

  private getSecretKey(): string {
    const key = this.configService.get<string>('TELEGRAM_SECRET_KEY');
    if (!key) {
      throw new Error('TELEGRAM_SECRET_KEY is not configured');
    }
    return key;
  }

  public async registerByTelegram(telegramChannelId: string): Promise<UserRecord> {
    const credentials = TelegramUtil.prepareCredentials(telegramChannelId, this.getSecretKey());
    const firebaseUser = await this.authService.registerFormFirebaseUserCreate({
      email: credentials.email,
      password: credentials.password,
    });
    return firebaseUser;
  }

  public async verifyIdToken(token: string): Promise<DecodedIdToken> {
    return await this.firebaseConfig
      .admin
      .auth()
      .verifyIdToken(token);
  }

  public async getOrCreateUserEntity(decodedToken: DecodedIdToken): Promise<UserI | null> {
    const existingUser = await this.userService.getUserByUid(decodedToken.uid);

    if (existingUser) {
      if (existingUser.status === UserStatuses.ACTIVE) {
        return existingUser;
      }
      this.logger.warn(`User with uid ${decodedToken.uid} is not active. Cannot create or return user.`);
      return null
    }

    const provider = UserUtil.findProvider(decodedToken);
    if (!provider) {
      this.logger.warn(`Cannot determine provider from decoded token for uid ${decodedToken.uid}`);
    }

    const newUser = await this.userService.create({
      uid: decodedToken.uid,
      displayName: decodedToken.name || Util.trimEmail(decodedToken.email),
      email: decodedToken.email,
      provider: provider,
      photoURL: decodedToken.picture,
    });
    return newUser;
  }

}