import { EmployeeProfileI, EmployeeProfileLocationOptions, EmployeeProfileStatuses } from "@shared/interfaces/EmployeeProfileI";
    
export const EmoployeeProfilesInitialData: EmployeeProfileI[] = [
    {
        uid: 'user1',
        displayName: 'John Doe',
        email: 'john.doe@example.com',
        firstName: 'John',
        lastName: 'Doe',
        residenceCountry: 'de',
        communicationLanguages: ['en', 'de'],
        locationOption: EmployeeProfileLocationOptions.ALL_EUROPE,
        status: EmployeeProfileStatuses.ACTIVE,
        employeeProfileId: 0,
        createdAt: new Date(),
        skills: ['ONE', 'TWO'],
        certificates: ['THREE', 'FOUR'],
    },
    {
        uid: 'user2',
        displayName: 'Anna Schmidt',
        email: 'anna.schmidt@example.com',
        firstName: 'Anna',
        lastName: 'Schmidt',
        residenceCountry: 'pl',
        communicationLanguages: ['pl', 'en'],
        locationOption: EmployeeProfileLocationOptions.DISTANCE,
        status: EmployeeProfileStatuses.ACTIVE,
        employeeProfileId: 1,
        createdAt: new Date(),
        skills: ['THREE', 'FOUR'],
        certificates: ['ONE', 'TWO'],
    },
    {
        uid: 'user3',
        displayName: 'Pierre Martin',
        email: 'pierre.martin@example.com',
        firstName: 'Pierre',
        lastName: 'Martin',
        residenceCountry: 'fr',
        communicationLanguages: ['fr', 'en'],
        locationOption: EmployeeProfileLocationOptions.SELECTED_COUNTRIES_EUROPE,
        status: EmployeeProfileStatuses.ACTIVE,
        employeeProfileId: 2,
        createdAt: new Date(),
        skills: ['FIVE', 'SIX'],
        certificates: ['FIVE', 'SIX'],
    },
    {
        uid: 'user4',
        displayName: 'Maria Rossi',
        email: 'maria.rossi@example.com',
        firstName: 'Maria',
        lastName: 'Rossi',
        residenceCountry: 'it',
        communicationLanguages: ['it', 'en'],
        locationOption: EmployeeProfileLocationOptions.ALL_EUROPE,
        status: EmployeeProfileStatuses.ACTIVE,
        employeeProfileId: 3,
        createdAt: new Date(),
        skills: ['SEVEN', 'ONE'],
        certificates: ['SEVEN', 'ONE'],
    },
    {
        uid: 'user5',
        displayName: 'Sofia Nowak',
        email: 'sofia.nowak@example.com',
        firstName: 'Sofia',
        lastName: 'Nowak',
        residenceCountry: 'pl',
        communicationLanguages: ['pl', 'de'],
        locationOption: EmployeeProfileLocationOptions.DISTANCE,
        status: EmployeeProfileStatuses.ACTIVE,
        employeeProfileId: 4,
        createdAt: new Date(),
        skills: ['TWO', 'THREE'],
        certificates: ['TWO', 'THREE'],
    },
    {
        uid: 'user6',
        displayName: 'Lucas Müller',
        email: 'lucas.mueller@example.com',
        firstName: 'Lucas',
        lastName: 'Müller',
        residenceCountry: 'de',
        communicationLanguages: ['de', 'en'],
        locationOption: EmployeeProfileLocationOptions.SELECTED_COUNTRIES_EUROPE,
        status: EmployeeProfileStatuses.ACTIVE,
        employeeProfileId: 5,
        createdAt: new Date(),
        skills: ['FOUR', 'FIVE'],
        certificates: ['FOUR', 'FIVE'],
    },
    {
        uid: 'user7',
        displayName: 'Elena García',
        email: 'elena.garcia@example.com',
        firstName: 'Elena',
        lastName: 'García',
        residenceCountry: 'es',
        communicationLanguages: ['es', 'en'],
        locationOption: EmployeeProfileLocationOptions.ALL_EUROPE,
        status: EmployeeProfileStatuses.ACTIVE,
        employeeProfileId: 6,
        createdAt: new Date(),
        skills: ['SIX', 'SEVEN'],
        certificates: ['SIX', 'SEVEN'],
    },
    {
        uid: 'user8',
        displayName: 'Marek Novak',
        email: 'marek.novak@example.com',
        firstName: 'Marek',
        lastName: 'Novak',
        residenceCountry: 'cz',
        communicationLanguages: ['cs', 'en'],
        locationOption: EmployeeProfileLocationOptions.DISTANCE,
        status: EmployeeProfileStatuses.ACTIVE,
        employeeProfileId: 7,
        createdAt: new Date(),
        skills: ['ONE', 'FIVE'],
        certificates: ['ONE', 'FIVE'],
    },
    {
        uid: 'user9',
        displayName: 'Katarzyna Zielinska',
        email: 'katarzyna.zielinska@example.com',
        firstName: 'Katarzyna',
        lastName: 'Zielinska',
        residenceCountry: 'pl',
        communicationLanguages: ['pl', 'en'],
        locationOption: EmployeeProfileLocationOptions.ALL_EUROPE,
        status: EmployeeProfileStatuses.ACTIVE,
        employeeProfileId: 8,
        createdAt: new Date(),
        skills: ['THREE', 'SEVEN'],
        certificates: ['THREE', 'SEVEN'],
    },
]