import { OfferEntity } from "offer/model/OfferEntity";
import { DeepPartial } from "typeorm";
import { AdminUtil } from "admin/AdminUtil";
import { Currencies, OfferStatuses } from "@shared/interfaces/OfferI";

const getCreatedAt = (idx: number): Date => AdminUtil.getRandomizedCreatedAt(idx);

const getDate = (year: number, month: number, day: number): Date => {
    return new Date(Date.UTC(year, month - 1, day, 8, 0, 0, 0));
};

const pickFromCycle = <T>(items: T[], index: number): T => items[index % items.length];

const locationPool = [
    { country: "pl", address: "Gdynia Shipyard, Poland", label: "Gdynia", coordinates: [18.673, 54.518] },
    { country: "gb", address: "Hull Offshore Yard, United Kingdom", label: "Hull", coordinates: [-0.322, 53.744] },
    { country: "de", address: "Bremerhaven Wind Hub, Germany", label: "Bremerhaven", coordinates: [8.574, 53.539] },
    { country: "no", address: "Hammerfest Offshore Base, Norway", label: "Hammerfest", coordinates: [23.682, 70.661] },
    { country: "se", address: "Visby Port Cranes, Sweden", label: "Visby", coordinates: [18.296, 57.634] },
    { country: "es", address: "Bilbao Coastal Works, Spain", label: "Bilbao", coordinates: [-2.934, 43.263] },
    { country: "pt", address: "Setúbal Industrial Dock, Portugal", label: "Setúbal", coordinates: [-8.891, 38.523] },
    { country: "fr", address: "Brest Offshore Campus, France", label: "Brest", coordinates: [-4.486, 48.390] },
    { country: "ie", address: "Cork Harbour Shipyard, Ireland", label: "Cork", coordinates: [-8.470, 51.898] },
    { country: "dk", address: "Aalborg Wind Terminal, Denmark", label: "Aalborg", coordinates: [9.921, 57.048] },
];

const languagePool: string[][] = [
    ["en", "pl"],
    ["en", "de"],
    ["en", "es"],
    ["en", "fr"],
    ["en", "no"],
    ["en", "pt"],
    ["en", "da"],
    ["en"],
    ["pl", "en"],
    ["de", "en"],
];

const categoryPool: OfferEntity["category"][] = [
    "WORK_PLATFORM",
    "LIFT",
    "SCAFFOLD",
    "LADDERS",
];

const categoryLabels: Record<OfferEntity["category"], string> = {
    WORK_PLATFORM: "Rope Access",
    LIFT: "Lift Maintenance",
    SCAFFOLD: "Scaffolding",
    LADDERS: "Rigging",
};

const descriptionPool = [
    "Assist with high-access inspections on critical infrastructure.",
    "Support routine maintenance for offshore assets requiring rope access.",
    "Execute composite repairs and minor fabrication at height.",
    "Coordinate site safety and supervise vertical access crews.",
    "Inspect structural joints and document findings for engineering teams.",
    "Install temporary rigging and fall arrest systems on industrial sites.",
    "Provide rope rescue cover and toolbox talks for shift teams.",
    "Perform cleaning and coating works on exposed structural elements.",
    "Monitor weather windows and prepare equipment for suspended operations.",
    "Audit PPE compliance and support onboarding of new technicians.",
];

const phoneNumberPool = [
    { prefix: "+48", number: "123456789" },
    { prefix: "+44", number: "7987654321" },
    { prefix: "+49", number: "30123456789" },
    { prefix: "+47", number: "98123456" },
    { prefix: "+46", number: "701234567" },
    { prefix: "+34", number: "612345678" },
    { prefix: "+351", number: "912345678" },
    { prefix: "+33", number: "612345678" },
    { prefix: "+353", number: "871234567" },
    { prefix: "+45", number: "12345678" },
];

export const OffersInitialData = (): DeepPartial<OfferEntity>[] => {
    const result: DeepPartial<OfferEntity>[] = [
        {
            uid: "company-001",
            status: OfferStatuses.ACTIVE,
            category: "WORK_PLATFORM",
            locationCountry: "pl",
            displayAddress: "Gdansk Shipyard, Poland",
            point: { type: "Point", coordinates: [18.649, 54.352] },
            startDate: getDate(2026, 1, 10),
            availableSlots: 6,
            appliedSlots: 2,
            acceptedSlots: 1,
            languagesRequired: ["en", "pl"],
            phoneNumber: { prefix: "+48", number: "123456789" },
            salary: 3200,
            currency: Currencies.EUR,
            displayName: "Rope Access Lead - Gdansk",
            description: "Inspect shipyard cranes and supervise rope access crew.",
            uniqueViewsCount: 3,
            createdAt: getCreatedAt(0),
            updatedAt: getDate(2025, 12, 1),
        },
        {
            uid: "company-002",
            status: OfferStatuses.ACTIVE,
            category: "LIFT",
            locationCountry: "dk",
            displayAddress: "Esbjerg Offshore Base, Denmark",
            startDate: getDate(2026, 3, 1),
            availableSlots: 12,
            appliedSlots: 4,
            acceptedSlots: 2,
            languagesRequired: ["en", "da"],
            phoneNumber: { prefix: "+45", number: "12345678" },
            salary: 4800,
            currency: Currencies.EUR,
            displayName: "Offshore Wind Turbine Technician",
            description: "Routine maintenance on offshore turbines with 14 days on/14 off rotation.",
            uniqueViewsCount: 4,
            createdAt: getCreatedAt(1),
            updatedAt: getDate(2025, 12, 4),
        },
        {
            uid: "company-003",
            status: OfferStatuses.ACTIVE,
            category: "SCAFFOLD",
            locationCountry: "de",
            displayAddress: "Alexanderplatz, Berlin",
            startDate: getDate(2026, 4, 12),
            availableSlots: 8,
            appliedSlots: 1,
            acceptedSlots: 0,
            languagesRequired: ["de", "en"],
            phoneNumber: { prefix: "+49", number: "30123456789" },
            salary: 27,
            currency: Currencies.EUR,
            displayName: "High-Rise Window Cleaning Crew",
            description: "Spring facade cleaning for Berlin skyline properties.",
            uniqueViewsCount: 3,
            createdAt: getCreatedAt(2),
            updatedAt: getDate(2025, 11, 28),
        },
        {
            uid: "company-004",
            status: OfferStatuses.INACTIVE,
            category: "WORK_PLATFORM",
            locationCountry: "at",
            displayAddress: "Innsbruck Ski Resort, Austria",
            startDate: getDate(2026, 1, 5),
            availableSlots: 5,
            appliedSlots: 0,
            acceptedSlots: 0,
            languagesRequired: ["de", "en"],
            phoneNumber: { prefix: "+43", number: "6601234567" },
            salary: 3800,
            currency: Currencies.EUR,
            displayName: "Rope Rescue Support for Ski Patrol",
            description: "Provide rope rescue cover during peak ski season.",
            uniqueViewsCount: 2,
            createdAt: getCreatedAt(3),
        },
        {
            uid: "company-005",
            status: OfferStatuses.ACTIVE,
            category: "LADDERS",
            locationCountry: "no",
            displayAddress: "Stavanger Offshore Platform",
            startDate: getDate(2026, 6, 10),
            availableSlots: 10,
            appliedSlots: 3,
            acceptedSlots: 1,
            languagesRequired: ["en", "no"],
            phoneNumber: { prefix: "+47", number: "98123456" },
            salary: 42,
            currency: Currencies.EUR,
            displayName: "Offshore Rope Access Welder",
            description: "Execute hot work scopes on semi-submersible rigs.",
            uniqueViewsCount: 3,
            createdAt: getCreatedAt(4),
        },
        {
            uid: "company-006",
            status: OfferStatuses.ACTIVE,
            category: "LIFT",
            locationCountry: "ch",
            displayAddress: "Zurich Communication Tower",
            startDate: getDate(2026, 5, 14),
            availableSlots: 4,
            appliedSlots: 0,
            acceptedSlots: 0,
            languagesRequired: ["de", "en"],
            phoneNumber: { prefix: "+41", number: "791234567" },
            salary: 35,
            currency: Currencies.EUR,
            displayName: "Telecom Tower Service Team",
            description: "Upgrade RF equipment on 150m telecom structure.",
            uniqueViewsCount: 2,
            createdAt: getCreatedAt(5),
        },
        {
            uid: "company-007",
            status: OfferStatuses.ACTIVE,
            category: "SCAFFOLD",
            locationCountry: "pt",
            displayAddress: "Ponte 25 de Abril, Lisbon",
            startDate: getDate(2026, 2, 18),
            availableSlots: 7,
            appliedSlots: 2,
            acceptedSlots: 0,
            languagesRequired: ["pt", "en"],
            phoneNumber: { prefix: "+351", number: "912345678" },
            salary: 34,
            currency: Currencies.EUR,
            displayName: "Bridge Structural Inspectors",
            description: "Carry out ultrasonic weld inspections on suspension bridge.",
            uniqueViewsCount: 3,
            createdAt: getCreatedAt(6),
        },
        {
            uid: "company-008",
            status: OfferStatuses.ACTIVE,
            category: "WORK_PLATFORM",
            locationCountry: "es",
            displayAddress: "Barcelona Adventure Park",
            startDate: getDate(2026, 5, 1),
            availableSlots: 9,
            appliedSlots: 1,
            acceptedSlots: 0,
            languagesRequired: ["es", "en"],
            phoneNumber: { prefix: "+34", number: "612345678" },
            salary: 3400,
            currency: Currencies.EUR,
            displayName: "Theme Park Ride Maintenance",
            description: "Pre-season maintenance for rides requiring work at height.",
            uniqueViewsCount: 3,
            createdAt: getCreatedAt(7),
        },
        {
            uid: "company-009",
            status: OfferStatuses.ACTIVE,
            category: "LADDERS",
            locationCountry: "pl",
            displayAddress: "Warsaw National Stadium",
            startDate: getDate(2026, 6, 20),
            availableSlots: 15,
            appliedSlots: 5,
            acceptedSlots: 2,
            languagesRequired: ["pl", "en"],
            phoneNumber: { prefix: "+48", number: "501123456" },
            salary: 22,
            currency: Currencies.EUR,
            displayName: "Concert Rigging Crew",
            description: "Install stage banners and lighting for summer concerts.",
            uniqueViewsCount: 4,
            createdAt: getCreatedAt(8),
        },
        {
            uid: "company-010",
            status: OfferStatuses.ACTIVE,
            category: "SCAFFOLD",
            locationCountry: "no",
            displayAddress: "Rjukan Hydroelectric Dam",
            startDate: getDate(2026, 8, 1),
            availableSlots: 6,
            appliedSlots: 0,
            acceptedSlots: 0,
            languagesRequired: ["en", "no"],
            phoneNumber: { prefix: "+47", number: "40123456" },
            salary: 5400,
            currency: Currencies.EUR,
            displayName: "Hydroelectric Dam Rope Team",
            description: "Perform concrete refurbishment on spillway walls.",
            uniqueViewsCount: 3,
            createdAt: getCreatedAt(9),
        },
        {
            uid: "company-011",
            status: OfferStatuses.ACTIVE,
            category: "WORK_PLATFORM",
            locationCountry: "gb",
            displayAddress: "Aberdeen North Sea Platform",
            startDate: getDate(2026, 7, 10),
            availableSlots: 18,
            appliedSlots: 6,
            acceptedSlots: 3,
            languagesRequired: ["en"],
            phoneNumber: { prefix: "+44", number: "7987654321" },
            salary: 37,
            currency: Currencies.EUR,
            displayName: "Offshore Rope Access Painters",
            description: "Splash zone blasting and coating scope on fixed platform.",
            uniqueViewsCount: 4,
            createdAt: getCreatedAt(10),
        },
        {
            uid: "company-012",
            status: OfferStatuses.INACTIVE,
            category: "LADDERS",
            locationCountry: "cz",
            displayAddress: "Prague Old Town Cathedral",
            startDate: getDate(2025, 12, 20),
            availableSlots: 3,
            appliedSlots: 0,
            acceptedSlots: 0,
            languagesRequired: ["cs", "en"],
            phoneNumber: { prefix: "+420", number: "602123456" },
            salary: 20,
            currency: Currencies.EUR,
            displayName: "Cathedral Facade Specialists",
            description: "Holiday campaign to restore gothic facade details.",
            uniqueViewsCount: 2,
            createdAt: getCreatedAt(11),
        },
        {
            uid: "company-013",
            status: OfferStatuses.ACTIVE,
            category: "LIFT",
            locationCountry: "nl",
            displayAddress: "Rotterdam Port Wind Farm",
            startDate: getDate(2026, 4, 5),
            availableSlots: 11,
            appliedSlots: 3,
            acceptedSlots: 1,
            languagesRequired: ["en", "nl"],
            phoneNumber: { prefix: "+31", number: "612345678" },
            salary: 36,
            currency: Currencies.EUR,
            displayName: "Wind Blade Rope Repair Crew",
            description: "Blade inspection and composite repair campaign.",
            uniqueViewsCount: 3,
            createdAt: getCreatedAt(12),
        },
        {
            uid: "company-014",
            status: OfferStatuses.ACTIVE,
            category: "WORK_PLATFORM",
            locationCountry: "fr",
            displayAddress: "Lyon Training Center",
            startDate: getDate(2026, 3, 15),
            availableSlots: 16,
            appliedSlots: 8,
            acceptedSlots: 5,
            languagesRequired: ["fr", "en"],
            phoneNumber: { prefix: "+33", number: "612345678" },
            salary: 3100,
            currency: Currencies.EUR,
            displayName: "Advanced Rope Rescue Trainer",
            description: "Deliver 10 day IRATA L2/L3 refresher courses.",
            uniqueViewsCount: 3,
            createdAt: getCreatedAt(13),
        },
        {
            uid: "company-015",
            status: OfferStatuses.ACTIVE,
            category: "SCAFFOLD",
            locationCountry: "es",
            displayAddress: "Valencia Solar Farm",
            startDate: getDate(2026, 1, 22),
            availableSlots: 14,
            appliedSlots: 0,
            acceptedSlots: 0,
            languagesRequired: ["es", "en"],
            phoneNumber: { prefix: "+34", number: "689123456" },
            salary: 23,
            currency: Currencies.EUR,
            displayName: "Solar Canopy Installers",
            description: "Install elevated solar arrays requiring rope positioning.",
            uniqueViewsCount: 3,
            createdAt: getCreatedAt(14),
        },
        {
            uid: "company-016",
            status: OfferStatuses.ACTIVE,

            category: "LADDERS",
            locationCountry: "pt",
            displayAddress: "Porto River Bridge",
            startDate: getDate(2026, 9, 10),
            availableSlots: 5,
            appliedSlots: 0,
            acceptedSlots: 0,
            languagesRequired: ["pt", "en"],
            phoneNumber: { prefix: "+351", number: "987654321" },
            salary: 30,
            currency: Currencies.EUR,
            displayName: "Suspension Cable Inspectors",
            description: "Inspect and photograph suspension cables and nodes.",
            uniqueViewsCount: 2,
            createdAt: getCreatedAt(15),
        },
        {
            uid: "company-017",
            status: OfferStatuses.ACTIVE,
            category: "WORK_PLATFORM",
            locationCountry: "de",
            displayAddress: "Hamburg Research Mast",
            startDate: getDate(2026, 2, 8),
            availableSlots: 3,
            appliedSlots: 0,
            acceptedSlots: 0,
            languagesRequired: ["de", "en"],
            phoneNumber: { prefix: "+49", number: "40987654321" },
            salary: 27,
            currency: Currencies.EUR,
            displayName: "Met Mast Instrument Technicians",
            description: "Calibrate instruments on 200m meteorological mast.",
            uniqueViewsCount: 3,
            createdAt: getCreatedAt(16),
        },
        {
            uid: "company-018",
            status: OfferStatuses.ACTIVE,
            category: "SCAFFOLD",
            locationCountry: "pl",
            displayAddress: "Katowice Industrial Park",
            startDate: getDate(2026, 5, 20),
            availableSlots: 6,
            appliedSlots: 2,
            acceptedSlots: 1,
            languagesRequired: ["pl", "en"],
            phoneNumber: { prefix: "+48", number: "321654987" },
            salary: 25,
            currency: Currencies.EUR,
            displayName: "Industrial Chimney Inspectors",
            description: "Internal and external survey of twin chimneys.",
            uniqueViewsCount: 4,
            createdAt: getCreatedAt(17),
        },
        {
            uid: "company-019",
            status: OfferStatuses.ACTIVE,
            category: "LADDERS",
            locationCountry: "at",
            displayAddress: "Vienna City Center",
            startDate: getDate(2026, 3, 5),
            availableSlots: 4,
            appliedSlots: 0,
            acceptedSlots: 0,
            languagesRequired: ["de", "en"],
            phoneNumber: { prefix: "+43", number: "6609876543" },
            salary: 23,
            currency: Currencies.EUR,
            displayName: "Urban Art Installation Crew",
            description: "Install large format banners on heritage buildings.",
            uniqueViewsCount: 3,
            createdAt: getCreatedAt(18),
        },
        {
            uid: "company-020",
            status: OfferStatuses.ACTIVE,
            category: "LIFT",
            locationCountry: "ch",
            displayAddress: "Zermatt Alpine Gondola",
            startDate: getDate(2026, 10, 1),
            availableSlots: 5,
            appliedSlots: 1,
            acceptedSlots: 0,
            languagesRequired: ["de", "en"],
            phoneNumber: { prefix: "+41", number: "774567890" },
            salary: 4450,
            currency: Currencies.EUR,
            displayName: "Mountain Gondola Rope Access Technician",
            description: "Pre-winter overhaul of gondola line and towers.",
            uniqueViewsCount: 4,
            createdAt: getCreatedAt(19),
        },
    ]

    const baseIndex = result.length;

    const createGeneratedOffer = (index: number): DeepPartial<OfferEntity> => {
        const location = pickFromCycle(locationPool, index);
        const category = pickFromCycle(categoryPool, index + 1);
        const languageSet = pickFromCycle(languagePool, index + 2);
        const phoneNumber = pickFromCycle(phoneNumberPool, index);
        const status = index % 9 === 0 ? OfferStatuses.INACTIVE : OfferStatuses.ACTIVE;
        const globalIndex = baseIndex + index + 1;
        const startYear = 2026 + Math.floor(index / 48);
        const startMonth = (index % 12) + 1;
        const startDay = 4 + (index % 20);
        const startDate = getDate(startYear, startMonth, startDay);
        const availableSlots = 4 + (index % 11);
        const appliedSlots = Math.min(index % 6, availableSlots);
        const acceptedSlots = Math.min(Math.floor(appliedSlots / 2), appliedSlots);
        const salaryBase = 20 + (index % 11) * 2;
        const usesMonthlySalary = index % 3 === 0;
        const salary = usesMonthlySalary ? salaryBase * 100 : salaryBase;
        const description = `${pickFromCycle(descriptionPool, index)} Location: ${location.label}.`;
        const displayName = `${categoryLabels[category]} Crew - ${location.label}`;
        const uid = `company-${globalIndex.toString().padStart(3, "0")}`;
        const viewBase = 700 + index * 3;

        const offer: DeepPartial<OfferEntity> = {
            uid,
            status,
            category,
            locationCountry: location.country,
            displayAddress: location.address,
            point: { type: "Point", coordinates: location.coordinates as [number, number] },
            startDate,
            availableSlots,
            appliedSlots,
            acceptedSlots,
            languagesRequired: languageSet,
            phoneNumber,
            salary,
            currency: Currencies.EUR,
            displayName,
            description,
            uniqueViewsCount: 3,
        };

        return offer;
    };

    const additionalOffers = Array.from({ length: 100 }, (_, index) => createGeneratedOffer(index));
    result.push(...additionalOffers);

    return result.map((offer, idx) => ({
        appliedSlots: 0,
        acceptedSlots: 0,
        ...offer,
        createdAt: offer.createdAt ?? getCreatedAt(idx),
    }));
}
